name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      function_description:
        description: "Description of the function"
        required: true
        default: "Deployed by GitHub Actions"

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    name: deploy lambda function
    environment: "CI/CD"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate branch
        run: |
          BRANCH="${{ github.ref_name }}"
          # If the branch is not 'main', verify it exists and matches 'rel/*'
          if [ "$BRANCH" != "main" ]; then
            if [[ "$BRANCH" != rel/* ]]; then
              echo "Invalid branch. Only 'main' or branches starting with 'rel/' are allowed."
              exit 1
            fi
            if ! git ls-remote --heads origin "$BRANCH" | grep -q "refs/heads/$BRANCH"; then
              echo "Branch '$BRANCH' not found in the repository."
              exit 1
            fi
          fi

      - name: Zip source code
        run: |
          cd src
          zip -r ../lambda_function.zip .

      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.AWS_LAMBDA_NAME }}
          zip_file: lambda_function.zip
          description: ${{ github.event.inputs.function_description }}
