name: Run Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "rel/*"
  push:
    branches:
      - "main"
      - "rel/*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r requirements.txt
          pip install pytest pytest-html

      - name: Run tests and generate HTML report
        run: |
          mkdir -p reports
          pytest --html=reports/test_report.html --self-contained-html

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/test_report.html

      - name: Create or update PR comment with test summary
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The test report artifact named **test-report** is available here: [Actions run page](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
